In [1]:
from Partition import *
from MaxCut import *
from numberpartitioning import karmarkar_karp

In [2]:
from IQP_circuit import *

In [3]:
n_qubits = 3
edges = [(0, 1), (1, 2), (0, 2)]

ops, coeffs = maxcut_obs(n_qubits, edges)
ops, coeffs

(array([[0, 0, 0],
        [1, 1, 0],
        [0, 1, 1],
        [1, 0, 1]]),
 array([-1.5,  0.5,  0.5,  0.5]))

In [4]:
n_qubits = 4

edges = [
    (0, 1),
    (1, 2),
    (2, 3),
    (3, 0),
]

ops, coeffs = maxcut_obs(n_qubits, edges)

print(ops)
print(coeffs)

[[0 0 0 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]
 [1 0 0 1]]
[-2.   0.5  0.5  0.5  0.5]


In [5]:
# Sparse graph
edges, weights = random_maxcut_instance(20, p=0.1, weighted = True, seed=42)

# Medium density
edges, weights = random_maxcut_instance(20, p=0.3, seed=42)

# Dense graph
edges, weights = random_maxcut_instance(20, p=0.7, seed=42)

In [6]:
n_qubits = 10
edges, weights = random_maxcut_instance(10, p=3/n_qubits, weighted = True, seed=42)
edges, weights

([(0, 5),
  (0, 8),
  (1, 7),
  (1, 8),
  (2, 9),
  (3, 4),
  (3, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (7, 8),
  (7, 9),
  (8, 9)],
 [6.0, 10.0, 1.0, 6.0, 4.0, 5.0, 8.0, 7.0, 7.0, 5.0, 3.0, 7.0, 9.0])

In [8]:
ops, coeffs = maxcut_obs(n_qubits, edges, weights)
ops, coeffs

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]]),
 array([-39. ,   3. ,   5. ,   0.5,   3. ,   2. ,   2.5,   4. ,   3.5,
          3.5,   2.5,   1.5,   3.5,   4.5]))

In [9]:
dataset = {}
num_example = 50
max_num_of_numbers = 10

for n in [3, 6, 9, 12, 15, 18, 21]:
    data = []
    count = 0
    print(n)
    while count < num_example:
        # datapoint = generate_unique_partition_instance(n, 
        #                                                min_value = 1, 
        #                                                max_value = 30)
        datapoint = np.random.randint(1, 100, n)
        result = karmarkar_karp(datapoint, num_parts = 2)
        if sum(result.partition[0]) == sum(result.partition[1]):
            data.append(datapoint.tolist())
            count += 1
            print(count, end = " ")
    print()
    dataset[n] = data

3
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
6
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
9
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
12
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
15
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
18
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 
21
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 4

In [10]:
import json

# Save dataset to disk
# data_json = [arr[i].tolist() for arr in dataset]
with open("partition.json", "w") as f:
    json.dump(dataset, f, indent=4)

print("Dataset saved to partition.json")

Dataset saved to partition.json


In [11]:
dataset = []
num_example = 20
count = 0
while count < num_example:
    data = np.random.randint(1, 100, 50)
    if sum(data) % 2 == 0:
        dataset.append(data)
        count += 1

In [12]:
import json

# Save dataset to disk
data_json = [arr.tolist() for arr in dataset]
with open("partition_50.json", "w") as f:
    json.dump(data_json, f, indent=4)

print("Dataset saved to partition_50.json")

Dataset saved to partition_50.json


In [14]:
from numberpartitioning import karmarkar_karp

for data in dataset:
    result = karmarkar_karp(data, num_parts=2)
    print(sum(result.partition[0]), sum(result.partition[1]))

1218 1218
1269 1269
1179 1179
1164 1164
1490 1490
1347 1347
1007 1007
1321 1321
1305 1305
1211 1211
1374 1374
1266 1266
1319 1319
1262 1262
1294 1294
1233 1233
1457 1457
1243 1243
1105 1105
1204 1204


In [15]:
np.sum(result.partition[0]), np.sum(result.partition[1])

(1204, 1204)

In [16]:
import numpy as np

In [17]:
dataset = {}
num_example = 50
max_num_of_numbers = 10

for n in [5, 10, 25, 50, 100]:
    count = 0
    data = []
    while count < num_example:
        arr = np.random.uniform(0, 1, n + n*(n-1)//2)
        data.append(arr.tolist())
        count += 1
    dataset[n] = data

In [18]:
import json

# Save dataset to disk
# data_json = [arr.tolist() for arr in dataset]
with open("ising_50.json", "w") as f:
    json.dump(dataset, f, indent=4)

print("Dataset saved to ising_50.json")

Dataset saved to ising_50.json


In [19]:
import numpy as np 

dataset = {}
num_example = 50

for n in [3, 6, 9, 12, 15, 18, 21]:
    count = 0
    data = []
    while count < num_example:
        arr = np.random.uniform(0, 1, n + n*(n-1)//2)
        data.append(arr.tolist())
        count += 1
    dataset[n] = data

In [20]:
import json

with open("ising.json", "w") as f:
    json.dump(dataset, f, indent=4)

print("Dataset saved to ising.json")

Dataset saved to ising.json


In [21]:
import numpy as np 

dataset = {}
num_example = 50

for n in [3, 6, 9, 12, 15, 18, 21]:
    count = 0
    data = []
    while count < num_example:
        edges, weights = random_maxcut_instance(n, p=3/n, weighted = True)
        data.append([edges, weights])
        count += 1
    dataset[n] = data

In [22]:
import json

with open("maxcut.json", "w") as f:
    json.dump(dataset, f, indent=4)

print("Dataset saved to maxcut.json")

Dataset saved to maxcut.json
